config/routes.rb
Rails.application.routes.draw do
  resources :borrowings

  resources :members

  resources :albums

  resources :artists

end

app/models/borrowing.rb
class Borrowing < ActiveRecord::Base
  belongs_to :member
  belongs_to :album
  before_create do |time|
  time.borrowing_date = Time.now
  end
end

app/controllers/borrowings_controller.rb
class BorrowingsController < ApplicationController
  before_action :set_borrowing, only: [:show, :edit, :update, :destroy]

  # GET /borrowings
  # GET /borrowings.json
  def index
    @borrowings = Borrowing.all
  end

  # GET /borrowings/1
  # GET /borrowings/1.json
  def show
  end

  # GET /borrowings/new
  def new
    @borrowing = Borrowing.new
  end

  # GET /borrowings/1/edit
  def edit
  end

  # POST /borrowings
  # POST /borrowings.json
  def create
    @borrowing = Borrowing.new(borrowing_params)

    respond_to do |format|
      if @borrowing.save
        format.html { redirect_to @borrowing, notice: 'Borrowing was successfully created.' }
        format.json { render :show, status: :created, location: @borrowing }
      else
        format.html { render :new }
        format.json { render json: @borrowing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borrowings/1
  # PATCH/PUT /borrowings/1.json
  def update
    respond_to do |format|
      if @borrowing.update(borrowing_params)
        format.html { redirect_to @borrowing, notice: 'Borrowing was successfully updated.' }
        format.json { render :show, status: :ok, location: @borrowing }
      else
        format.html { render :edit }
        format.json { render json: @borrowing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrowings/1
  # DELETE /borrowings/1.json
  def destroy
    @borrowing.destroy
    respond_to do |format|
      format.html { redirect_to borrowings_url, notice: 'Borrowing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrowing
      @borrowing = Borrowing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def borrowing_params
      params.require(:borrowing).permit(:member_id, :album_id, :back_date)
    end
end

app/helpers/borrowings_helper.rb
module BorrowingsHelper
end

app/views/borrowings/_form.html.erb
<%= form_for(@borrowing) do |f| %>
  <% if @borrowing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@borrowing.errors.count, "error") %> prohibited this borrowing from being saved:</h2>

      <ul>
      <% @borrowing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member_id %><br>
    <%= f.collection_select(:member_id, Member.all, :id, :last_name, prompt: "choisissez un membre") %>
  </div>
  <div class="field">
    <%= f.label :album_id %><br>
    <%= f.collection_select(:album_id ,Album.all, :id, :title, prompt: "choisissez un album" ) %>
  </div>
  <div class="field">
    <%= f.label :back_date %><br>
    <%= f.date_select :back_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/borrowings/edit.html.erb
<h1>Editing borrowing</h1>

<%= render 'form' %>

<%= link_to 'Show', @borrowing %> |
<%= link_to 'Back', borrowings_path %>

app/views/borrowings/index.html.erb
<h1 class="centre">Listing borrowings</h1>

<table class="centre">
  <thead>
    <tr>
      <th>Member</th>
      <th>Album</th>
      <th>Borrowing date</th>
      <th>Back date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @borrowings.each do |borrowing| %>
      <tr>
        <td><%= borrowing.member_id %></td>
        <td><%= borrowing.album_id %></td>
        <td><%= borrowing.borrowing_date %></td>
        <td><%= borrowing.back_date %></td>
        <td><%= link_to 'Show', borrowing %></td>
        <td><%= link_to 'Edit', edit_borrowing_path(borrowing) %></td>
        <td><%= link_to 'Destroy', borrowing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p class="centre">
<%= link_to 'New Borrowing', new_borrowing_path %>
</p>

app/views/borrowings/new.html.erb
<h1>New borrowing</h1>

<%= render 'form' %>

<%= link_to 'Back', borrowings_path %>

app/views/borrowings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @borrowing.member_id %>
</p>

<p>
  <strong>Album:</strong>
  <%= @borrowing.album_id %>
</p>

<p>
  <strong>Borrowing date:</strong>
  <%= @borrowing.borrowing_date %>
</p>

<p>
  <strong>Back date:</strong>
  <%= @borrowing.back_date %>
</p>

<%= link_to 'Edit', edit_borrowing_path(@borrowing) %> |
<%= link_to 'Back', borrowings_path %>