config/routes.rb
Rails.application.routes.draw do
  resources :borrowings

  resources :members

  resources :albums

  resources :artists

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :borrowings
  validates :first_name, presence:true
  validates :last_name, presence:true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :email)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1 class="centre">Listing members</h1>

<table class="centre">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.first_name %></td>
        <td><%= member.last_name %></td>
        <td><%= member.email %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p class="centre">
<%= link_to 'New Member', new_member_path %>
<p>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>